version: "3.4"

services:
  app:
    image: logapp:v6
    build:
      context: ./app
      dockerfile: Dockerfile
      
    ports:
      - 5000:5000
    volumes:
      - .:/app:cached
    env_file: .env