name: Run unit tests

on:
  workflow_dispatch:
  push:
    branches: [ dev ]
  pull_request:
    types: [ opened, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose

      - name: Generate required .env file
        run: |
          echo DEBUG=True >> .env
          echo FLASK_DEBUG=1 >> .env
          echo FLASK_APP=run.py >> .env
          echo MYSQL_HOST=db >> .env
          echo MYSQL_USER=flask >> .env
          echo MYSQL_PASSWORD=12345678 >> .env
          echo MYSQL_DATABASE=geeklogin >> .env
          echo MYSQL_PORT=3306 >> .env

      - name: Build Docker containers
        run: docker-compose -f docker-compose.yml build

      - name: Run tests
        run: docker-compose -f docker-compose.yml run --rm web pytest
